import { Founder, Mentor } from "./types";

export const mentors: Mentor[] = [
  {
    id: "m1",
    name: "Elena Voss",
    avatar: "/avatars/mentor-1.jpg",
    contacts: { email: "elena@vertexventures.com", linkedin: "linkedin.com/in/elenavoss", twitter: "@elenavoss", phone: "+1-212-555-0101" },
    current_role: "Managing Partner",
    company: "Vertex Ventures",
    bio: "Former CTO turned VC. Led 3 companies from seed to Series B. Deep expertise in B2B SaaS infrastructure and developer tools. Passionate about helping technical founders navigate the fundraising landscape.",
    years_experience: 18,
    industries: ["saas", "ai-ml", "cybersecurity"],
    expertise: ["fundraising", "technical", "hiring"],
    preferred_stages: ["seed", "series-a"],
    looks_for_in_founders: ["technical depth", "coachability", "market clarity"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["deal-flow", "giving-back"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    location: "New York, USA",
    languages: ["English", "German"],
    skills: ["fundraising strategy", "board management", "technical due diligence", "SaaS metrics", "team scaling"],
    notable_achievements: ["Led $2B+ in exits", "Former CTO at DataStack (acq. by Oracle)", "Board member at 5 public companies"],
    portfolio_companies: ["Vercel", "Snyk", "DataStack"],
    sessions_completed: 47,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-15",
  },
  {
    id: "m2",
    name: "Carlos Mendez",
    avatar: "/avatars/mentor-2.jpg",
    contacts: { email: "carlos@finstack.io", linkedin: "linkedin.com/in/carlosmendez", twitter: "@carlosmendez", phone: "+52-55-5555-0202", website: "carlosmendez.com" },
    current_role: "CEO & Founder",
    company: "FinStack (acquired by Stripe)",
    bio: "Built and sold a fintech startup for $200M. Expert in payments infrastructure, regulatory compliance, and scaling operations in Latin America. Now advising the next generation of LatAm founders.",
    years_experience: 15,
    industries: ["fintech", "marketplace"],
    expertise: ["fundraising", "go-to-market", "legal-compliance", "international-expansion"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["grit", "market insight", "execution speed"],
    max_mentees: 4,
    current_mentees: 2,
    motivation: ["giving-back", "networking"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["Spanish", "English", "Portuguese"],
    skills: ["payments infrastructure", "LatAm regulatory", "M&A", "founder coaching", "cross-border operations"],
    notable_achievements: ["Sold FinStack to Stripe for $200M", "Forbes 30 Under 30 LatAm", "Scaled to 12 countries in 3 years"],
    portfolio_companies: ["Clip", "Konfio", "Nubank"],
    sessions_completed: 89,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-11-20",
  },
  {
    id: "m3",
    name: "Dr. Amara Okonkwo",
    avatar: "/avatars/mentor-3.jpg",
    contacts: { email: "amara@biogenesis.com", linkedin: "linkedin.com/in/amaraokonkwo", website: "biogenesislabs.com" },
    current_role: "Chief Science Officer",
    company: "BioGenesis Labs",
    bio: "PhD in Computational Biology, 12 patents. Transitioned from academia to biotech entrepreneurship. Specializes in helping deep-tech founders bridge the gap between research and commercialization.",
    years_experience: 20,
    industries: ["biotech", "healthtech", "deeptech"],
    expertise: ["technical", "fundraising", "partnerships"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["scientific rigor", "vision", "coachability"],
    max_mentees: 2,
    current_mentees: 1,
    motivation: ["giving-back", "sector-learning"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "Europe/London",
    location: "London, UK",
    languages: ["English", "Igbo", "French"],
    skills: ["computational biology", "IP strategy", "grant writing", "scientific publishing", "regulatory pathways"],
    notable_achievements: ["12 patents filed", "Nature publications", "Raised $80M for BioGenesis"],
    portfolio_companies: ["BioGenesis Labs", "GenVault"],
    sessions_completed: 31,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-03-01",
  },
  {
    id: "m4",
    name: "Raj Patel",
    avatar: "/avatars/mentor-4.jpg",
    contacts: { email: "raj@cloudflare.com", linkedin: "linkedin.com/in/rajpatel-eng", twitter: "@rajpatel_eng" },
    current_role: "VP of Engineering",
    company: "Cloudflare",
    bio: "Scaled engineering teams from 5 to 200+. Expert in distributed systems, infrastructure, and building high-performance engineering cultures. Previously founding engineer at two YC companies.",
    years_experience: 14,
    industries: ["saas", "cybersecurity", "ai-ml"],
    expertise: ["technical", "hiring", "operations", "leadership"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["technical excellence", "team building ability", "long-term vision"],
    max_mentees: 3,
    current_mentees: 2,
    motivation: ["giving-back", "advisory-equity"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "America/Los_Angeles",
    location: "San Francisco, USA",
    languages: ["English", "Hindi", "Gujarati"],
    skills: ["distributed systems", "engineering culture", "system design", "performance optimization", "technical interviews"],
    notable_achievements: ["Scaled Cloudflare eng from 50 to 200+", "YC W12 and S14 founding engineer", "Built systems serving 25M rps"],
    sessions_completed: 62,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-02-10",
  },
  {
    id: "m5",
    name: "Sofia Chen",
    avatar: "/avatars/mentor-5.jpg",
    contacts: { email: "sofia@growth-advisory.com", linkedin: "linkedin.com/in/sofiachen", twitter: "@sofiagrowthlead", website: "sofiachen.com" },
    current_role: "Growth Advisor",
    company: "Independent (ex-Uber, ex-Airbnb)",
    bio: "Led growth at Uber LATAM and Airbnb Experiences. Expert in marketplace dynamics, user acquisition, and go-to-market strategy for consumer-facing products. Fluent in Mandarin, English, and Spanish.",
    years_experience: 12,
    industries: ["marketplace", "ecommerce", "logistics"],
    expertise: ["go-to-market", "product-market-fit", "international-expansion", "operations"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["user empathy", "data-driven mindset", "hustle"],
    max_mentees: 5,
    current_mentees: 3,
    motivation: ["advisory-equity", "networking"],
    working_style: "strategic",
    meeting_frequency: "monthly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["English", "Spanish", "Mandarin"],
    skills: ["growth hacking", "marketplace dynamics", "unit economics", "A/B testing", "international GTM"],
    notable_achievements: ["Grew Uber LATAM from 0 to 5M rides/month", "Launched Airbnb Experiences in 15 cities", "Speaker at Growth Summit 2024"],
    sessions_completed: 104,
    avg_rating: 4.6,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-09-15",
  },
  {
    id: "m6",
    name: "Marcus Thompson",
    avatar: "/avatars/mentor-6.jpg",
    contacts: { email: "marcus@impactcapital.com", linkedin: "linkedin.com/in/marcusthompson", website: "impactcapital.fund" },
    current_role: "General Partner",
    company: "Impact Capital Fund",
    bio: "20 years in impact investing. Focus on climate tech and social enterprises. Has helped 30+ startups raise over $500M combined. Board member at three public benefit corporations.",
    years_experience: 22,
    industries: ["climate", "social-impact", "edtech"],
    expertise: ["fundraising", "leadership", "partnerships", "legal-compliance"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["mission alignment", "scalability thinking", "resilience"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["giving-back", "deal-flow"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Chicago",
    location: "Chicago, USA",
    languages: ["English"],
    skills: ["impact measurement", "ESG frameworks", "board governance", "nonprofit-to-startup transitions", "climate policy"],
    notable_achievements: ["$500M+ raised for portfolio", "Board of 3 public benefit corps", "UN Climate Advisor"],
    sessions_completed: 73,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-05",
  },
  {
    id: "m7",
    name: "Yuki Tanaka",
    avatar: "/avatars/mentor-7.jpg",
    contacts: { email: "yuki@tri.global", linkedin: "linkedin.com/in/yukitanaka-ai", twitter: "@yukitanaka_ai" },
    current_role: "Head of AI",
    company: "Toyota Research Institute",
    bio: "Leading AI researcher with 50+ publications. Built ML teams at Google Brain and Toyota. Specializes in applied AI, computer vision, and the path from research prototype to production ML system.",
    years_experience: 16,
    industries: ["ai-ml", "deeptech", "logistics"],
    expertise: ["technical", "hiring", "product-market-fit"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["technical depth", "research credibility", "product sense"],
    max_mentees: 2,
    current_mentees: 0,
    motivation: ["sector-learning", "giving-back"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "Asia/Tokyo",
    location: "Tokyo, Japan",
    languages: ["English", "Japanese"],
    skills: ["computer vision", "NLP", "MLOps", "research-to-product", "AI safety", "robotics"],
    notable_achievements: ["50+ publications (h-index 38)", "Led Google Brain robotics team", "2 best paper awards at NeurIPS"],
    sessions_completed: 28,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-04-20",
  },
  {
    id: "m8",
    name: "Priya Sharma",
    avatar: "/avatars/mentor-8.jpg",
    contacts: { email: "priya@razorpay.com", linkedin: "linkedin.com/in/priyasharma-ops", phone: "+91-98-5555-0808" },
    current_role: "COO",
    company: "Razorpay",
    bio: "Operational leader who scaled Razorpay from 50 to 3000 employees. Expert in fintech operations, compliance across multiple markets, and building systems that scale. Former McKinsey consultant.",
    years_experience: 13,
    industries: ["fintech", "saas", "marketplace"],
    expertise: ["operations", "hiring", "legal-compliance", "leadership"],
    preferred_stages: ["series-a", "series-b+"],
    looks_for_in_founders: ["operational maturity", "delegation skills", "market timing"],
    max_mentees: 2,
    current_mentees: 1,
    motivation: ["networking", "giving-back"],
    working_style: "balanced",
    meeting_frequency: "monthly",
    timezone: "Asia/Kolkata",
    location: "Bangalore, India",
    languages: ["English", "Hindi", "Marathi"],
    skills: ["ops scaling", "compliance frameworks", "organizational design", "process automation", "risk management"],
    notable_achievements: ["Scaled Razorpay from 50 to 3000 people", "McKinsey engagement manager", "Launched in 5 new markets"],
    sessions_completed: 36,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-02-28",
  },
  {
    id: "m9",
    name: "David Kimura",
    avatar: "/avatars/mentor-9.jpg",
    contacts: { email: "david@edventure.io", linkedin: "linkedin.com/in/davidkimura", website: "edventure.io" },
    current_role: "Founder & CEO",
    company: "EdVenture (Series C)",
    bio: "Building the future of education technology. Former teacher turned entrepreneur. EdVenture serves 2M+ students across Latin America. Expert in edtech, social impact, and navigating government partnerships.",
    years_experience: 10,
    industries: ["edtech", "social-impact", "ai-ml"],
    expertise: ["product-market-fit", "go-to-market", "partnerships", "fundraising"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["mission-driven", "user empathy", "scrappiness"],
    max_mentees: 4,
    current_mentees: 2,
    motivation: ["giving-back", "sector-learning"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Sao_Paulo",
    location: "Sao Paulo, Brazil",
    languages: ["English", "Japanese", "Portuguese", "Spanish"],
    skills: ["edtech product design", "government sales", "impact measurement", "community building", "content strategy"],
    notable_achievements: ["2M+ students served", "Series C at $150M valuation", "Former Teach For All fellow"],
    portfolio_companies: ["EdVenture"],
    sessions_completed: 55,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-12-10",
  },
  {
    id: "m10",
    name: "Natasha Petrov",
    avatar: "/avatars/mentor-10.jpg",
    contacts: { email: "natasha@datadog.com", linkedin: "linkedin.com/in/natashapetrov", twitter: "@natashacyber" },
    current_role: "CISO",
    company: "Datadog",
    bio: "Cybersecurity leader with experience at NSA, Google, and Datadog. Expert in security architecture, compliance frameworks, and building security-first cultures. Angel investor in 15+ security startups.",
    years_experience: 17,
    industries: ["cybersecurity", "saas", "fintech"],
    expertise: ["technical", "fundraising", "legal-compliance", "hiring"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["domain expertise", "technical credibility", "customer obsession"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["deal-flow", "advisory-equity"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    location: "Washington D.C., USA",
    languages: ["English", "Russian", "Ukrainian"],
    skills: ["security architecture", "SOC2/ISO27001", "pen testing", "threat modeling", "zero trust"],
    notable_achievements: ["Angel investor in 15+ security startups", "Former NSA analyst", "Built Datadog security from scratch"],
    sessions_completed: 41,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-03-15",
  },
  {
    id: "m11",
    name: "Ana Lucia Torres",
    avatar: "/avatars/mentor-11.jpg",
    contacts: { email: "analucia@allvp.com", linkedin: "linkedin.com/in/analuciat", twitter: "@analuciat_vc", website: "allvp.com" },
    current_role: "Venture Partner",
    company: "ALLVP",
    bio: "One of LatAm's most active early-stage investors. Led investments in Kavak, Clip, and Bitso. Deep understanding of the Mexican and Latin American startup ecosystem. Stanford MBA.",
    years_experience: 14,
    industries: ["fintech", "marketplace", "ecommerce", "logistics"],
    expertise: ["fundraising", "go-to-market", "international-expansion", "partnerships"],
    preferred_stages: ["pre-seed", "seed"],
    looks_for_in_founders: ["market insight", "execution speed", "LatAm expertise"],
    max_mentees: 5,
    current_mentees: 3,
    motivation: ["deal-flow", "networking"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["Spanish", "English", "French"],
    skills: ["LatAm market entry", "term sheet negotiation", "cap table strategy", "investor relations", "pitch coaching"],
    notable_achievements: ["Led investments in Kavak, Clip, Bitso", "Stanford MBA", "Top 50 LatAm VCs by Bloomberg"],
    portfolio_companies: ["Kavak", "Clip", "Bitso", "Konfio"],
    sessions_completed: 92,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-10-01",
  },
  {
    id: "m12",
    name: "James O'Brien",
    avatar: "/avatars/mentor-12.jpg",
    contacts: { email: "james@stripe.com", linkedin: "linkedin.com/in/jamesobrien-eng", twitter: "@jamesobrien_dev" },
    current_role: "CTO",
    company: "Stripe",
    bio: "Payments infrastructure architect. Built systems processing $1T+ annually. Expert in API design, developer experience, and scaling engineering organizations. Frequent speaker at QCon and StrangeLoop.",
    years_experience: 19,
    industries: ["fintech", "saas", "ecommerce"],
    expertise: ["technical", "hiring", "operations", "product-market-fit"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["technical excellence", "developer empathy", "system thinking"],
    max_mentees: 2,
    current_mentees: 2,
    motivation: ["giving-back", "sector-learning"],
    working_style: "balanced",
    meeting_frequency: "monthly",
    timezone: "America/Los_Angeles",
    location: "San Francisco, USA",
    languages: ["English", "Irish"],
    skills: ["API design", "payments systems", "developer experience", "distributed systems", "technical writing"],
    notable_achievements: ["Built systems processing $1T+ annually", "Speaker at QCon, StrangeLoop", "Author of 'APIs at Scale'"],
    sessions_completed: 44,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-20",
  },
];

export const founders: Founder[] = [
  {
    id: "f1",
    name: "Isabella Reyes",
    avatar: "/avatars/founder-1.jpg",
    contacts: { email: "isabella@meditrack.health", linkedin: "linkedin.com/in/isabellareyes", phone: "+52-55-5555-1001", website: "meditrack.health" },
    company: "MediTrack",
    one_liner: "AI-powered medication adherence platform for chronic disease patients in LatAm",
    bio: "Former physician who saw firsthand how patients struggle with complex medication regimens. Building MediTrack to use AI reminders and pharmacy integrations to improve adherence rates by 40%.",
    stage: "seed",
    industry: "healthtech",
    business_model: "b2b2c",
    team_size: 6,
    team_composition: "mixed",
    challenges: ["go-to-market", "fundraising", "partnerships"],
    looking_for: ["go-to-market", "fundraising", "partnerships"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["Spanish", "English"],
    funding_raised: "$500K",
    revenue_stage: "early-revenue",
    pitch_deck_url: "https://pitch.com/demo-meditrack",
    video_url: "https://youtube.com/watch?v=demo",
    skills: ["healthcare", "AI/ML", "product management", "clinical research"],
    created_at: "2024-06-01",
  },
  {
    id: "f2",
    name: "Alex Kim",
    avatar: "/avatars/founder-2.jpg",
    contacts: { email: "alex@codeforge.dev", linkedin: "linkedin.com/in/alexkim-dev", twitter: "@alexkim_dev", website: "codeforge.dev" },
    company: "CodeForge",
    one_liner: "No-code platform for building enterprise internal tools with AI assistance",
    bio: "Ex-Google engineer who spent years watching teams reinvent the same internal tools. CodeForge lets any employee build enterprise-grade tools with natural language, reducing IT backlog by 60%.",
    stage: "series-a",
    industry: "saas",
    business_model: "b2b-saas",
    team_size: 22,
    team_composition: "technical",
    challenges: ["hiring", "operations", "go-to-market"],
    looking_for: ["hiring", "operations", "go-to-market"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Los_Angeles",
    location: "San Francisco, USA",
    languages: ["English", "Korean"],
    funding_raised: "$8M",
    revenue_stage: "$1M-$10M ARR",
    pitch_deck_url: "https://pitch.com/demo-codeforge",
    skills: ["software engineering", "AI/ML", "enterprise sales", "developer tools"],
    created_at: "2024-04-15",
  },
  {
    id: "f3",
    name: "Camila Herrera",
    avatar: "/avatars/founder-3.jpg",
    contacts: { email: "camila@tierraverde.co", linkedin: "linkedin.com/in/camilaherrera", website: "tierraverde.co" },
    company: "TierraVerde",
    one_liner: "Carbon credit marketplace connecting LatAm regenerative farms with global buyers",
    bio: "Environmental engineer and third-generation farmer. Building a transparent, blockchain-verified carbon credit marketplace that ensures fair prices for smallholder farmers while providing verifiable offsets.",
    stage: "pre-seed",
    industry: "climate",
    business_model: "marketplace",
    team_size: 3,
    team_composition: "mixed",
    challenges: ["fundraising", "product-market-fit", "legal-compliance"],
    looking_for: ["fundraising", "product-market-fit", "legal-compliance"],
    working_style: "balanced",
    meeting_frequency: "weekly",
    timezone: "America/Bogota",
    location: "Bogota, Colombia",
    languages: ["Spanish", "English"],
    funding_raised: "$50K (grants)",
    revenue_stage: "pre-revenue",
    video_url: "https://youtube.com/watch?v=demo-tierraverde",
    skills: ["environmental science", "agriculture", "blockchain", "carbon markets"],
    created_at: "2024-08-10",
  },
  {
    id: "f4",
    name: "Daniel Okafor",
    avatar: "/avatars/founder-4.jpg",
    contacts: { email: "daniel@paybridge.io", linkedin: "linkedin.com/in/danielokafor", twitter: "@danielokafor_fin", phone: "+52-55-5555-1004" },
    company: "PayBridge",
    one_liner: "Cross-border payment rails for Africa-LatAm trade corridors",
    bio: "Nigerian-Mexican fintech operator. Previously led expansion at a payments unicorn. PayBridge reduces the cost of Africa-LatAm B2B payments by 70% using stablecoin settlement and local banking partnerships.",
    stage: "seed",
    industry: "fintech",
    business_model: "api-platform",
    team_size: 8,
    team_composition: "technical",
    challenges: ["legal-compliance", "international-expansion", "fundraising"],
    looking_for: ["legal-compliance", "international-expansion", "fundraising"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["English", "Spanish", "Yoruba"],
    funding_raised: "$1.2M",
    revenue_stage: "early-revenue",
    pitch_deck_url: "https://pitch.com/demo-paybridge",
    skills: ["payments", "crypto/stablecoins", "regulatory compliance", "cross-border ops"],
    created_at: "2024-05-20",
  },
  {
    id: "f5",
    name: "Maria Santos",
    avatar: "/avatars/founder-5.jpg",
    contacts: { email: "maria@neurolearn.ai", linkedin: "linkedin.com/in/mariasantos-neuro", website: "neurolearn.ai" },
    company: "NeuroLearn",
    one_liner: "Adaptive learning platform using neuroscience insights for K-12 students",
    bio: "Neuroscience PhD dropout who pivoted to edtech. NeuroLearn adapts content difficulty and presentation style in real-time based on student engagement signals. Piloting in 15 schools across Mexico.",
    stage: "pre-seed",
    industry: "edtech",
    business_model: "b2b2c",
    team_size: 4,
    team_composition: "technical",
    challenges: ["product-market-fit", "fundraising", "go-to-market"],
    looking_for: ["product-market-fit", "fundraising", "go-to-market"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    location: "Guadalajara, Mexico",
    languages: ["Spanish", "English"],
    funding_raised: "$100K",
    revenue_stage: "pre-revenue",
    video_url: "https://youtube.com/watch?v=demo-neurolearn",
    skills: ["neuroscience", "machine learning", "education", "UX research"],
    created_at: "2024-07-01",
  },
  {
    id: "f6",
    name: "Ryan Park",
    avatar: "/avatars/founder-6.jpg",
    contacts: { email: "ryan@shieldai-sec.com", linkedin: "linkedin.com/in/ryanpark-sec", twitter: "@ryanpark_cyber" },
    company: "ShieldAI Security",
    one_liner: "Automated penetration testing platform powered by LLMs",
    bio: "Former red team lead at CrowdStrike. ShieldAI uses large language models to autonomously discover and exploit vulnerabilities, generating remediation reports that junior devs can action immediately.",
    stage: "seed",
    industry: "cybersecurity",
    business_model: "b2b-saas",
    team_size: 10,
    team_composition: "technical",
    challenges: ["go-to-market", "hiring", "fundraising"],
    looking_for: ["go-to-market", "hiring", "fundraising"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    location: "New York, USA",
    languages: ["English", "Korean"],
    funding_raised: "$2.5M",
    revenue_stage: "<$1M ARR",
    pitch_deck_url: "https://pitch.com/demo-shieldai",
    skills: ["cybersecurity", "LLMs", "red teaming", "enterprise sales", "security compliance"],
    created_at: "2024-03-25",
  },
  {
    id: "f7",
    name: "Lucia Fernandez",
    avatar: "/avatars/founder-7.jpg",
    contacts: { email: "lucia@freshroute.com", linkedin: "linkedin.com/in/luciafernandez", phone: "+55-11-5555-1007", website: "freshroute.com" },
    company: "FreshRoute",
    one_liner: "AI-optimized cold chain logistics for perishable goods in Latin America",
    bio: "Supply chain expert who worked at Amazon and Mercado Libre. FreshRoute cuts food waste by 35% through predictive routing, temperature monitoring, and dynamic pricing for last-mile delivery.",
    stage: "series-a",
    industry: "logistics",
    business_model: "b2b-saas",
    team_size: 30,
    team_composition: "mixed",
    challenges: ["operations", "international-expansion", "hiring"],
    looking_for: ["operations", "international-expansion", "hiring"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Sao_Paulo",
    location: "Sao Paulo, Brazil",
    languages: ["Portuguese", "English", "Spanish"],
    funding_raised: "$12M",
    revenue_stage: "$1M-$10M ARR",
    skills: ["supply chain", "IoT", "machine learning", "logistics operations"],
    created_at: "2024-02-14",
  },
  {
    id: "f8",
    name: "Omar Al-Rashid",
    avatar: "/avatars/founder-8.jpg",
    contacts: { email: "omar@propchain.io", linkedin: "linkedin.com/in/omaralrashid", twitter: "@omar_propchain" },
    company: "PropChain",
    one_liner: "Fractional real estate investment platform for emerging markets",
    bio: "Ex-Goldman Sachs real estate analyst. PropChain tokenizes commercial real estate, allowing retail investors to buy fractional shares starting at $100. Operating in Mexico, Colombia, and Brazil.",
    stage: "seed",
    industry: "proptech",
    business_model: "marketplace",
    team_size: 12,
    team_composition: "business",
    challenges: ["technical", "legal-compliance", "fundraising"],
    looking_for: ["technical", "legal-compliance", "fundraising"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    location: "Monterrey, Mexico",
    languages: ["Arabic", "English", "Spanish"],
    funding_raised: "$3M",
    revenue_stage: "early-revenue",
    pitch_deck_url: "https://pitch.com/demo-propchain",
    video_url: "https://youtube.com/watch?v=demo-propchain",
    skills: ["real estate finance", "tokenization", "regulatory", "Goldman Sachs"],
    created_at: "2024-04-01",
  },
  {
    id: "f9",
    name: "Aisha Patel",
    avatar: "/avatars/founder-9.jpg",
    contacts: { email: "aisha@genomicsai.com", linkedin: "linkedin.com/in/aishapatel-bio" },
    company: "GenomicsAI",
    one_liner: "Affordable genetic testing and personalized medicine for underserved populations",
    bio: "Biomedical engineer from MIT. GenomicsAI makes genetic testing 90% cheaper through novel ML-based analysis, bringing personalized medicine to populations historically excluded from genomic research.",
    stage: "idea",
    industry: "biotech",
    business_model: "b2b2c",
    team_size: 2,
    team_composition: "technical",
    challenges: ["fundraising", "technical", "partnerships"],
    looking_for: ["fundraising", "technical", "partnerships"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/New_York",
    location: "Boston, USA",
    languages: ["English", "Hindi", "Gujarati"],
    revenue_stage: "pre-revenue",
    video_url: "https://youtube.com/watch?v=demo-genomicsai",
    skills: ["genomics", "bioinformatics", "machine learning", "clinical trials"],
    created_at: "2024-09-01",
  },
  {
    id: "f10",
    name: "Mateo Gonzalez",
    avatar: "/avatars/founder-10.jpg",
    contacts: { email: "mateo@campushub.mx", linkedin: "linkedin.com/in/mateogonzalez", twitter: "@mateo_campus" },
    company: "CampusHub",
    one_liner: "All-in-one student life platform connecting university services and community",
    bio: "Built a 50K-user student app at his university. CampusHub is the super-app for college life: class scheduling, study groups, campus events, marketplace, and mental health resources in one place.",
    stage: "pre-seed",
    industry: "edtech",
    business_model: "b2b2c",
    team_size: 5,
    team_composition: "technical",
    challenges: ["go-to-market", "product-market-fit", "fundraising"],
    looking_for: ["go-to-market", "product-market-fit", "fundraising"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    location: "Mexico City, Mexico",
    languages: ["Spanish", "English"],
    funding_raised: "$75K",
    revenue_stage: "pre-revenue",
    skills: ["mobile development", "community building", "student engagement", "React Native"],
    created_at: "2024-07-15",
  },
  {
    id: "f11",
    name: "Sarah Mitchell",
    avatar: "/avatars/founder-11.jpg",
    contacts: { email: "sarah@greengrid.io", linkedin: "linkedin.com/in/sarahmitchell-energy", website: "greengrid.io" },
    company: "GreenGrid",
    one_liner: "Smart energy management for commercial buildings using IoT and ML",
    bio: "Former Tesla energy division engineer. GreenGrid's IoT sensors and ML models reduce commercial building energy consumption by 25-40%, paying for themselves in under 6 months.",
    stage: "seed",
    industry: "climate",
    business_model: "b2b-saas",
    team_size: 14,
    team_composition: "technical",
    challenges: ["go-to-market", "partnerships", "hiring"],
    looking_for: ["go-to-market", "partnerships", "hiring"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/Denver",
    location: "Denver, USA",
    languages: ["English"],
    funding_raised: "$4M",
    revenue_stage: "<$1M ARR",
    pitch_deck_url: "https://pitch.com/demo-greengrid",
    skills: ["energy systems", "IoT", "machine learning", "hardware-software integration"],
    created_at: "2024-03-10",
  },
  {
    id: "f12",
    name: "Jorge Ramirez",
    avatar: "/avatars/founder-12.jpg",
    contacts: { email: "jorge@mercadoai.com", linkedin: "linkedin.com/in/jorgeramirez", twitter: "@jorge_mercadoai" },
    company: "MercadoAI",
    one_liner: "AI copilot for small merchants selling on Latin American marketplaces",
    bio: "Former Mercado Libre product manager. MercadoAI helps small sellers optimize listings, pricing, and inventory using AI — turning corner store owners into ecommerce power sellers.",
    stage: "pre-seed",
    industry: "ecommerce",
    business_model: "b2b-saas",
    team_size: 4,
    team_composition: "mixed",
    challenges: ["product-market-fit", "fundraising", "go-to-market"],
    looking_for: ["product-market-fit", "fundraising", "go-to-market"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Buenos_Aires",
    location: "Buenos Aires, Argentina",
    languages: ["Spanish", "English", "Portuguese"],
    funding_raised: "$60K",
    revenue_stage: "pre-revenue",
    video_url: "https://youtube.com/watch?v=demo-mercadoai",
    skills: ["ecommerce", "AI/ML", "marketplace dynamics", "product management"],
    created_at: "2024-08-20",
  },
];
