import { Founder, Mentor } from "./types";

export const mentors: Mentor[] = [
  {
    id: "m1",
    name: "Elena Voss",
    avatar: "/avatars/mentor-1.jpg",
    email: "elena@example.com",
    current_role: "Managing Partner",
    company: "Vertex Ventures",
    bio: "Former CTO turned VC. Led 3 companies from seed to Series B. Deep expertise in B2B SaaS infrastructure and developer tools. Passionate about helping technical founders navigate the fundraising landscape.",
    years_experience: 18,
    industries: ["saas", "ai-ml", "cybersecurity"],
    expertise: ["fundraising", "technical", "hiring"],
    preferred_stages: ["seed", "series-a"],
    looks_for_in_founders: ["technical depth", "coachability", "market clarity"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["deal-flow", "giving-back"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    sessions_completed: 47,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-15",
  },
  {
    id: "m2",
    name: "Carlos Mendez",
    avatar: "/avatars/mentor-2.jpg",
    email: "carlos@example.com",
    current_role: "CEO & Founder",
    company: "FinStack (acquired by Stripe)",
    bio: "Built and sold a fintech startup for $200M. Expert in payments infrastructure, regulatory compliance, and scaling operations in Latin America. Now advising the next generation of LatAm founders.",
    years_experience: 15,
    industries: ["fintech", "marketplace"],
    expertise: ["fundraising", "go-to-market", "legal-compliance", "international-expansion"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["grit", "market insight", "execution speed"],
    max_mentees: 4,
    current_mentees: 2,
    motivation: ["giving-back", "networking"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    sessions_completed: 89,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-11-20",
  },
  {
    id: "m3",
    name: "Dr. Amara Okonkwo",
    avatar: "/avatars/mentor-3.jpg",
    email: "amara@example.com",
    current_role: "Chief Science Officer",
    company: "BioGenesis Labs",
    bio: "PhD in Computational Biology, 12 patents. Transitioned from academia to biotech entrepreneurship. Specializes in helping deep-tech founders bridge the gap between research and commercialization.",
    years_experience: 20,
    industries: ["biotech", "healthtech", "deeptech"],
    expertise: ["technical", "fundraising", "partnerships"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["scientific rigor", "vision", "coachability"],
    max_mentees: 2,
    current_mentees: 1,
    motivation: ["giving-back", "sector-learning"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "Europe/London",
    sessions_completed: 31,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-03-01",
  },
  {
    id: "m4",
    name: "Raj Patel",
    avatar: "/avatars/mentor-4.jpg",
    email: "raj@example.com",
    current_role: "VP of Engineering",
    company: "Cloudflare",
    bio: "Scaled engineering teams from 5 to 200+. Expert in distributed systems, infrastructure, and building high-performance engineering cultures. Previously founding engineer at two YC companies.",
    years_experience: 14,
    industries: ["saas", "cybersecurity", "ai-ml"],
    expertise: ["technical", "hiring", "operations", "leadership"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["technical excellence", "team building ability", "long-term vision"],
    max_mentees: 3,
    current_mentees: 2,
    motivation: ["giving-back", "advisory-equity"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "America/Los_Angeles",
    sessions_completed: 62,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-02-10",
  },
  {
    id: "m5",
    name: "Sofia Chen",
    avatar: "/avatars/mentor-5.jpg",
    email: "sofia@example.com",
    current_role: "Growth Advisor",
    company: "Independent (ex-Uber, ex-Airbnb)",
    bio: "Led growth at Uber LATAM and Airbnb Experiences. Expert in marketplace dynamics, user acquisition, and go-to-market strategy for consumer-facing products. Fluent in Mandarin, English, and Spanish.",
    years_experience: 12,
    industries: ["marketplace", "ecommerce", "logistics"],
    expertise: ["go-to-market", "product-market-fit", "international-expansion", "operations"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["user empathy", "data-driven mindset", "hustle"],
    max_mentees: 5,
    current_mentees: 3,
    motivation: ["advisory-equity", "networking"],
    working_style: "strategic",
    meeting_frequency: "monthly",
    timezone: "America/Mexico_City",
    sessions_completed: 104,
    avg_rating: 4.6,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-09-15",
  },
  {
    id: "m6",
    name: "Marcus Thompson",
    avatar: "/avatars/mentor-6.jpg",
    email: "marcus@example.com",
    current_role: "General Partner",
    company: "Impact Capital Fund",
    bio: "20 years in impact investing. Focus on climate tech and social enterprises. Has helped 30+ startups raise over $500M combined. Board member at three public benefit corporations.",
    years_experience: 22,
    industries: ["climate", "social-impact", "edtech"],
    expertise: ["fundraising", "leadership", "partnerships", "legal-compliance"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["mission alignment", "scalability thinking", "resilience"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["giving-back", "deal-flow"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Chicago",
    sessions_completed: 73,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-05",
  },
  {
    id: "m7",
    name: "Yuki Tanaka",
    avatar: "/avatars/mentor-7.jpg",
    email: "yuki@example.com",
    current_role: "Head of AI",
    company: "Toyota Research Institute",
    bio: "Leading AI researcher with 50+ publications. Built ML teams at Google Brain and Toyota. Specializes in applied AI, computer vision, and the path from research prototype to production ML system.",
    years_experience: 16,
    industries: ["ai-ml", "deeptech", "logistics"],
    expertise: ["technical", "hiring", "product-market-fit"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["technical depth", "research credibility", "product sense"],
    max_mentees: 2,
    current_mentees: 0,
    motivation: ["sector-learning", "giving-back"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "Asia/Tokyo",
    sessions_completed: 28,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-04-20",
  },
  {
    id: "m8",
    name: "Priya Sharma",
    avatar: "/avatars/mentor-8.jpg",
    email: "priya@example.com",
    current_role: "COO",
    company: "Razorpay",
    bio: "Operational leader who scaled Razorpay from 50 to 3000 employees. Expert in fintech operations, compliance across multiple markets, and building systems that scale. Former McKinsey consultant.",
    years_experience: 13,
    industries: ["fintech", "saas", "marketplace"],
    expertise: ["operations", "hiring", "legal-compliance", "leadership"],
    preferred_stages: ["series-a", "series-b+"],
    looks_for_in_founders: ["operational maturity", "delegation skills", "market timing"],
    max_mentees: 2,
    current_mentees: 1,
    motivation: ["networking", "giving-back"],
    working_style: "balanced",
    meeting_frequency: "monthly",
    timezone: "Asia/Kolkata",
    sessions_completed: 36,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-02-28",
  },
  {
    id: "m9",
    name: "David Kimura",
    avatar: "/avatars/mentor-9.jpg",
    email: "david@example.com",
    current_role: "Founder & CEO",
    company: "EdVenture (Series C)",
    bio: "Building the future of education technology. Former teacher turned entrepreneur. EdVenture serves 2M+ students across Latin America. Expert in edtech, social impact, and navigating government partnerships.",
    years_experience: 10,
    industries: ["edtech", "social-impact", "ai-ml"],
    expertise: ["product-market-fit", "go-to-market", "partnerships", "fundraising"],
    preferred_stages: ["idea", "pre-seed", "seed"],
    looks_for_in_founders: ["mission-driven", "user empathy", "scrappiness"],
    max_mentees: 4,
    current_mentees: 2,
    motivation: ["giving-back", "sector-learning"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Sao_Paulo",
    sessions_completed: 55,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-12-10",
  },
  {
    id: "m10",
    name: "Natasha Petrov",
    avatar: "/avatars/mentor-10.jpg",
    email: "natasha@example.com",
    current_role: "CISO",
    company: "Datadog",
    bio: "Cybersecurity leader with experience at NSA, Google, and Datadog. Expert in security architecture, compliance frameworks, and building security-first cultures. Angel investor in 15+ security startups.",
    years_experience: 17,
    industries: ["cybersecurity", "saas", "fintech"],
    expertise: ["technical", "fundraising", "legal-compliance", "hiring"],
    preferred_stages: ["pre-seed", "seed", "series-a"],
    looks_for_in_founders: ["domain expertise", "technical credibility", "customer obsession"],
    max_mentees: 3,
    current_mentees: 1,
    motivation: ["deal-flow", "advisory-equity"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    sessions_completed: 41,
    avg_rating: 4.7,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-03-15",
  },
  {
    id: "m11",
    name: "Ana Lucia Torres",
    avatar: "/avatars/mentor-11.jpg",
    email: "analucia@example.com",
    current_role: "Venture Partner",
    company: "ALLVP",
    bio: "One of LatAm's most active early-stage investors. Led investments in Kavak, Clip, and Bitso. Deep understanding of the Mexican and Latin American startup ecosystem. Stanford MBA.",
    years_experience: 14,
    industries: ["fintech", "marketplace", "ecommerce", "logistics"],
    expertise: ["fundraising", "go-to-market", "international-expansion", "partnerships"],
    preferred_stages: ["pre-seed", "seed"],
    looks_for_in_founders: ["market insight", "execution speed", "LatAm expertise"],
    max_mentees: 5,
    current_mentees: 3,
    motivation: ["deal-flow", "networking"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    sessions_completed: 92,
    avg_rating: 4.9,
    calendly_url: "https://calendly.com/demo",
    created_at: "2023-10-01",
  },
  {
    id: "m12",
    name: "James O'Brien",
    avatar: "/avatars/mentor-12.jpg",
    email: "james@example.com",
    current_role: "CTO",
    company: "Stripe",
    bio: "Payments infrastructure architect. Built systems processing $1T+ annually. Expert in API design, developer experience, and scaling engineering organizations. Frequent speaker at QCon and StrangeLoop.",
    years_experience: 19,
    industries: ["fintech", "saas", "ecommerce"],
    expertise: ["technical", "hiring", "operations", "product-market-fit"],
    preferred_stages: ["seed", "series-a", "series-b+"],
    looks_for_in_founders: ["technical excellence", "developer empathy", "system thinking"],
    max_mentees: 2,
    current_mentees: 2,
    motivation: ["giving-back", "sector-learning"],
    working_style: "balanced",
    meeting_frequency: "monthly",
    timezone: "America/Los_Angeles",
    sessions_completed: 44,
    avg_rating: 4.8,
    calendly_url: "https://calendly.com/demo",
    created_at: "2024-01-20",
  },
];

export const founders: Founder[] = [
  {
    id: "f1",
    name: "Isabella Reyes",
    avatar: "/avatars/founder-1.jpg",
    email: "isabella@example.com",
    company: "MediTrack",
    one_liner: "AI-powered medication adherence platform for chronic disease patients in LatAm",
    bio: "Former physician who saw firsthand how patients struggle with complex medication regimens. Building MediTrack to use AI reminders and pharmacy integrations to improve adherence rates by 40%.",
    stage: "seed",
    industry: "healthtech",
    business_model: "b2b2c",
    team_size: 6,
    team_composition: "mixed",
    challenges: ["go-to-market", "fundraising", "partnerships"],
    looking_for: ["go-to-market", "fundraising", "partnerships"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    website: "https://meditrack.example.com",
    created_at: "2024-06-01",
  },
  {
    id: "f2",
    name: "Alex Kim",
    avatar: "/avatars/founder-2.jpg",
    email: "alex@example.com",
    company: "CodeForge",
    one_liner: "No-code platform for building enterprise internal tools with AI assistance",
    bio: "Ex-Google engineer who spent years watching teams reinvent the same internal tools. CodeForge lets any employee build enterprise-grade tools with natural language, reducing IT backlog by 60%.",
    stage: "series-a",
    industry: "saas",
    business_model: "b2b-saas",
    team_size: 22,
    team_composition: "technical",
    challenges: ["hiring", "operations", "go-to-market"],
    looking_for: ["hiring", "operations", "go-to-market"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Los_Angeles",
    website: "https://codeforge.example.com",
    created_at: "2024-04-15",
  },
  {
    id: "f3",
    name: "Camila Herrera",
    avatar: "/avatars/founder-3.jpg",
    email: "camila@example.com",
    company: "TierraVerde",
    one_liner: "Carbon credit marketplace connecting LatAm regenerative farms with global buyers",
    bio: "Environmental engineer and third-generation farmer. Building a transparent, blockchain-verified carbon credit marketplace that ensures fair prices for smallholder farmers while providing verifiable offsets.",
    stage: "pre-seed",
    industry: "climate",
    business_model: "marketplace",
    team_size: 3,
    team_composition: "mixed",
    challenges: ["fundraising", "product-market-fit", "legal-compliance"],
    looking_for: ["fundraising", "product-market-fit", "legal-compliance"],
    working_style: "balanced",
    meeting_frequency: "weekly",
    timezone: "America/Bogota",
    created_at: "2024-08-10",
  },
  {
    id: "f4",
    name: "Daniel Okafor",
    avatar: "/avatars/founder-4.jpg",
    email: "daniel@example.com",
    company: "PayBridge",
    one_liner: "Cross-border payment rails for Africa-LatAm trade corridors",
    bio: "Nigerian-Mexican fintech operator. Previously led expansion at a payments unicorn. PayBridge reduces the cost of Africa-LatAm B2B payments by 70% using stablecoin settlement and local banking partnerships.",
    stage: "seed",
    industry: "fintech",
    business_model: "api-platform",
    team_size: 8,
    team_composition: "technical",
    challenges: ["legal-compliance", "international-expansion", "fundraising"],
    looking_for: ["legal-compliance", "international-expansion", "fundraising"],
    working_style: "hands-on",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    created_at: "2024-05-20",
  },
  {
    id: "f5",
    name: "Maria Santos",
    avatar: "/avatars/founder-5.jpg",
    email: "maria@example.com",
    company: "NeuroLearn",
    one_liner: "Adaptive learning platform using neuroscience insights for K-12 students",
    bio: "Neuroscience PhD dropout who pivoted to edtech. NeuroLearn adapts content difficulty and presentation style in real-time based on student engagement signals. Piloting in 15 schools across Mexico.",
    stage: "pre-seed",
    industry: "edtech",
    business_model: "b2b2c",
    team_size: 4,
    team_composition: "technical",
    challenges: ["product-market-fit", "fundraising", "go-to-market"],
    looking_for: ["product-market-fit", "fundraising", "go-to-market"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    created_at: "2024-07-01",
  },
  {
    id: "f6",
    name: "Ryan Park",
    avatar: "/avatars/founder-6.jpg",
    email: "ryan@example.com",
    company: "ShieldAI Security",
    one_liner: "Automated penetration testing platform powered by LLMs",
    bio: "Former red team lead at CrowdStrike. ShieldAI uses large language models to autonomously discover and exploit vulnerabilities, generating remediation reports that junior devs can action immediately.",
    stage: "seed",
    industry: "cybersecurity",
    business_model: "b2b-saas",
    team_size: 10,
    team_composition: "technical",
    challenges: ["go-to-market", "hiring", "fundraising"],
    looking_for: ["go-to-market", "hiring", "fundraising"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/New_York",
    created_at: "2024-03-25",
  },
  {
    id: "f7",
    name: "Lucia Fernandez",
    avatar: "/avatars/founder-7.jpg",
    email: "lucia@example.com",
    company: "FreshRoute",
    one_liner: "AI-optimized cold chain logistics for perishable goods in Latin America",
    bio: "Supply chain expert who worked at Amazon and Mercado Libre. FreshRoute cuts food waste by 35% through predictive routing, temperature monitoring, and dynamic pricing for last-mile delivery.",
    stage: "series-a",
    industry: "logistics",
    business_model: "b2b-saas",
    team_size: 30,
    team_composition: "mixed",
    challenges: ["operations", "international-expansion", "hiring"],
    looking_for: ["operations", "international-expansion", "hiring"],
    working_style: "strategic",
    meeting_frequency: "biweekly",
    timezone: "America/Sao_Paulo",
    created_at: "2024-02-14",
  },
  {
    id: "f8",
    name: "Omar Al-Rashid",
    avatar: "/avatars/founder-8.jpg",
    email: "omar@example.com",
    company: "PropChain",
    one_liner: "Fractional real estate investment platform for emerging markets",
    bio: "Ex-Goldman Sachs real estate analyst. PropChain tokenizes commercial real estate, allowing retail investors to buy fractional shares starting at $100. Operating in Mexico, Colombia, and Brazil.",
    stage: "seed",
    industry: "proptech",
    business_model: "marketplace",
    team_size: 12,
    team_composition: "business",
    challenges: ["technical", "legal-compliance", "fundraising"],
    looking_for: ["technical", "legal-compliance", "fundraising"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/Mexico_City",
    created_at: "2024-04-01",
  },
  {
    id: "f9",
    name: "Aisha Patel",
    avatar: "/avatars/founder-9.jpg",
    email: "aisha@example.com",
    company: "GenomicsAI",
    one_liner: "Affordable genetic testing and personalized medicine for underserved populations",
    bio: "Biomedical engineer from MIT. GenomicsAI makes genetic testing 90% cheaper through novel ML-based analysis, bringing personalized medicine to populations historically excluded from genomic research.",
    stage: "idea",
    industry: "biotech",
    business_model: "b2b2c",
    team_size: 2,
    team_composition: "technical",
    challenges: ["fundraising", "technical", "partnerships"],
    looking_for: ["fundraising", "technical", "partnerships"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/New_York",
    created_at: "2024-09-01",
  },
  {
    id: "f10",
    name: "Mateo Gonzalez",
    avatar: "/avatars/founder-10.jpg",
    email: "mateo@example.com",
    company: "CampusHub",
    one_liner: "All-in-one student life platform connecting university services and community",
    bio: "Built a 50K-user student app at his university. CampusHub is the super-app for college life: class scheduling, study groups, campus events, marketplace, and mental health resources in one place.",
    stage: "pre-seed",
    industry: "edtech",
    business_model: "b2b2c",
    team_size: 5,
    team_composition: "technical",
    challenges: ["go-to-market", "product-market-fit", "fundraising"],
    looking_for: ["go-to-market", "product-market-fit", "fundraising"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Mexico_City",
    created_at: "2024-07-15",
  },
  {
    id: "f11",
    name: "Sarah Mitchell",
    avatar: "/avatars/founder-11.jpg",
    email: "sarah@example.com",
    company: "GreenGrid",
    one_liner: "Smart energy management for commercial buildings using IoT and ML",
    bio: "Former Tesla energy division engineer. GreenGrid's IoT sensors and ML models reduce commercial building energy consumption by 25-40%, paying for themselves in under 6 months.",
    stage: "seed",
    industry: "climate",
    business_model: "b2b-saas",
    team_size: 14,
    team_composition: "technical",
    challenges: ["go-to-market", "partnerships", "hiring"],
    looking_for: ["go-to-market", "partnerships", "hiring"],
    working_style: "balanced",
    meeting_frequency: "biweekly",
    timezone: "America/Denver",
    created_at: "2024-03-10",
  },
  {
    id: "f12",
    name: "Jorge Ramirez",
    avatar: "/avatars/founder-12.jpg",
    email: "jorge@example.com",
    company: "MercadoAI",
    one_liner: "AI copilot for small merchants selling on Latin American marketplaces",
    bio: "Former Mercado Libre product manager. MercadoAI helps small sellers optimize listings, pricing, and inventory using AI—turning corner store owners into ecommerce power sellers.",
    stage: "pre-seed",
    industry: "ecommerce",
    business_model: "b2b-saas",
    team_size: 4,
    team_composition: "mixed",
    challenges: ["product-market-fit", "fundraising", "go-to-market"],
    looking_for: ["product-market-fit", "fundraising", "go-to-market"],
    working_style: "hands-on",
    meeting_frequency: "weekly",
    timezone: "America/Buenos_Aires",
    created_at: "2024-08-20",
  },
];
